### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by ty625911724** [Big-Brother-Pikachu/Where2edit#1]
Thanks a lot for your great works!

I notice that only test code is available currently. Do you plan to release training code?

Thanks! : )

**Comment by Big-Brother-Pikachu** [comment]
Hi, thanks for your attention! The training code is available in the attention folder, and you can try the default configuration in the [train_scripts.sh](https://github.com/Big-Brother-Pikachu/Where2edit/blob/master/attention/train_scripts.sh). Be free to communicate with us if you have further questions!

**Comment by ty625911724** [comment]
Thanks a lot for your helpful comments!
